import type { Metadata } from 'next';
import Script from 'next/script';
import { Anton, Inter, JetBrains_Mono } from 'next/font/google';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/react';
import './styles.css';
import './page-styles.css';

// Self-hosted via next/font: served from our own origin (no Google Fonts
// round-trip) with an automatic size-adjusted fallback (no layout shift / text
// flash). Exposed as CSS variables that the stylesheets reference.
const anton = Anton({ weight: '400', subsets: ['latin'], variable: '--font-anton', display: 'swap' });
const inter = Inter({ subsets: ['latin'], style: ['normal', 'italic'], variable: '--font-inter', display: 'swap' });
const jbMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono', display: 'swap' });

const SITE = 'https://sqbpictures.com';
const TITLE = "S'QB Pictures — Tell Your Story Today! | AI + Video Production";

// ── Google Search Console verification ───────────────────────────────────────
// 1. Go to https://search.google.com/search-console → add property
//    "https://sqbpictures.com" → choose the "HTML tag" method.
// 2. Google shows a tag like:
//    <meta name="google-site-verification" content="AbC123...xyz" />
// 3. Paste ONLY the content value (the part in quotes) between the quotes below,
//    then commit/deploy and click "Verify" in Search Console.
const GOOGLE_SITE_VERIFICATION = ''; // e.g. 'AbC123_paste_your_code_here_xyz'
const DESCRIPTION =
  "S'QB Pictures is an AI-first video production house in Delhi NCR and Mumbai — ad films, TVCs, AI films, music videos and branded series for India's biggest brands. Filmmakers first, AI operators second.";
const SAME_AS = [
  'https://www.instagram.com/sqbpictures/',
  'https://www.linkedin.com/company/sqbpictures/',
];

export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: {
    default: TITLE,
    template: "%s — S'QB Pictures",
  },
  description: DESCRIPTION,
  keywords: [
    "S'QB Pictures", 'AI production house', 'video production house',
    'best video production house in Delhi NCR', 'best AI production house',
    'AI video production house in India', 'AI production house India',
    'video production house Delhi NCR', 'AI video production company India',
    'video production company Delhi NCR', 'ad film production Delhi',
    'TVC production India', 'AI film studio', 'AI films India', 'music video',
    'branded series', 'vertical cinema', 'generative video', 'AI VFX',
    'Delhi NCR', 'Mumbai', 'India',
  ],
  applicationName: "S'QB Pictures",
  authors: [{ name: "S'QB Pictures" }],
  creator: "S'QB Pictures",
  publisher: "S'QB Pictures",
  alternates: { canonical: '/' },
  // Only emits the <meta name="google-site-verification"> tag once you paste a
  // code above — left empty it stays out of the HTML.
  ...(GOOGLE_SITE_VERIFICATION
    ? { verification: { google: GOOGLE_SITE_VERIFICATION } }
    : {}),
  // Favicon is served from app/icon.png + app/favicon.ico + app/apple-icon.png
  // (a tight square S'QB mark — the old full logo turned to mush at 16px, so
  // Google showed a generic globe). Next.js App Router auto-wires those files.
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 },
  },
  openGraph: {
    type: 'website',
    url: SITE,
    siteName: "S'QB Pictures",
    title: TITLE,
    description: DESCRIPTION,
    locale: 'en_IN',
    // og:image is generated by app/opengraph-image.tsx (a real 1200×630 card).
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
    // twitter:image is generated by app/twitter-image.tsx.
  },
};

// Structured data — one @graph so search engines + AI assistants understand the
// entity: who S'QB is (Organization), the site (WebSite), the production service
// (ProfessionalService, with the services + areas it covers), and plain-language
// answers (FAQPage) to the exact questions people / AI agents ask.
const JSONLD = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Organization',
      '@id': `${SITE}/#org`,
      name: "S'QB Pictures",
      alternateName: ['SQB Pictures', "S'QB"],
      url: SITE,
      logo: `${SITE}/logo-source.png`,
      image: `${SITE}/logo-dark.png`,
      description: DESCRIPTION,
      slogan: 'Tell Your Story Today',
      email: 'surajsharma@sqbpictures.com',
      founders: [
        { '@type': 'Person', name: 'Suraj Sharma' },
        { '@type': 'Person', name: 'Shubham Shah' },
      ],
      knowsAbout: [
        'AI video production', 'video production', 'ad films', 'TVC production',
        'AI films', 'VFX', 'music videos', 'vertical cinema', 'branded series',
      ],
      areaServed: ['Delhi NCR', 'Mumbai', 'India', 'IN', 'AE', 'SA', 'SG', 'GB', 'US'],
      address: { '@type': 'PostalAddress', addressCountry: 'IN', addressRegion: 'Delhi NCR / Mumbai' },
      sameAs: SAME_AS,
    },
    {
      '@type': 'WebSite',
      '@id': `${SITE}/#website`,
      url: SITE,
      name: "S'QB Pictures",
      publisher: { '@id': `${SITE}/#org` },
      inLanguage: 'en-IN',
    },
    {
      '@type': 'ProfessionalService',
      '@id': `${SITE}/#service`,
      name: "S'QB Pictures — AI & Video Production House",
      url: SITE,
      image: `${SITE}/logo-dark.png`,
      description: DESCRIPTION,
      parentOrganization: { '@id': `${SITE}/#org` },
      email: 'surajsharma@sqbpictures.com',
      areaServed: [
        { '@type': 'City', name: 'Delhi NCR' },
        { '@type': 'City', name: 'New Delhi' },
        { '@type': 'City', name: 'Gurugram' },
        { '@type': 'City', name: 'Noida' },
        { '@type': 'City', name: 'Mumbai' },
        { '@type': 'Country', name: 'India' },
      ],
      serviceType: [
        'AI video production', 'Video production', 'Ad film production',
        'TVC production', 'AI film production', 'Music video production',
        'VFX', 'Vertical and short-form content',
      ],
      sameAs: SAME_AS,
    },
    {
      '@type': 'FAQPage',
      '@id': `${SITE}/#faq`,
      mainEntity: [
        {
          '@type': 'Question',
          name: 'Is S’QB Pictures an AI production house?',
          acceptedAnswer: { '@type': 'Answer', text: "Yes. S'QB Pictures is an AI-first video and AI production house — it pairs cinematic, filmmaker-led craft with generative-AI pipelines to make ad films, TVCs, AI films, music videos and branded series." },
        },
        {
          '@type': 'Question',
          name: 'Is S’QB Pictures a good video production house in Delhi NCR?',
          acceptedAnswer: { '@type': 'Answer', text: "S'QB Pictures is a Delhi NCR and Mumbai based video production house that has delivered work for some of India's biggest brands, spanning ad films, TVCs, AI films and music videos." },
        },
        {
          '@type': 'Question',
          name: 'What does S’QB Pictures produce?',
          acceptedAnswer: { '@type': 'Answer', text: 'Ad films and TVCs, AI films, music videos, branded and original series, VFX and vertical / short-form content for brands and platforms.' },
        },
        {
          '@type': 'Question',
          name: 'Where is S’QB Pictures located?',
          acceptedAnswer: { '@type': 'Answer', text: "S'QB Pictures operates out of Delhi NCR and Mumbai and produces work for clients across India and overseas." },
        },
      ],
    },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="dark" className={`${anton.variable} ${inter.variable} ${jbMono.variable}`}>
      <head>
        {/* Fonts are self-hosted via next/font (see imports) — no external font
            request, and a size-adjusted fallback prevents layout shift. */}

        {/* Connect early to the video / image hosts so embeds start sooner. */}
        <link rel="preconnect" href="https://player.vimeo.com" />
        <link rel="preconnect" href="https://i.vimeocdn.com" crossOrigin="anonymous" />
        <link rel="preconnect" href="https://www.youtube-nocookie.com" />
        <link rel="preconnect" href="https://drive.google.com" />
        <link rel="dns-prefetch" href="https://i.ytimg.com" />
        <link rel="dns-prefetch" href="https://vumbnail.com" />

        <link rel="preload" href="/logo-dark.png" as="image" />
        <link rel="preload" href="/logo-footer.png" as="image" />

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(JSONLD) }}
        />
      </head>
      <body>
        {children}
        {/* Vimeo SDK — used by the case-study player for mute control */}
        <Script src="https://player.vimeo.com/api/player.js" strategy="afterInteractive" />
        {/* Real-user performance (LCP/CLS/INP) + traffic — active on Vercel. */}
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
